# Generated by Django 4.0.3 on 2022-03-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='UID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
