# Generated by Django 4.0.3 on 2022-03-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_rating_professor_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='professor_uid',
            field=models.CharField(max_length=20),
        ),
    ]
